select * from employee;
select first_name,last_name from employee;
select upper(first_name) from employee;
select lower(first_name) from employee;
select distinct department from employee;
select left(first_name,3) from employee;
select instr(first_name, 'o') from employee where first_name='John';
select rtrim(first_name) from employee;
select ltrim(first_name) from employee;
select length(first_name) from employee;
select replace(first_name, 'o', '$') from employee;
select concat(first_name, '_', last_name) from employee;
select first_name,extract(year from joining_date),extract(month from joining_date),extract(day from joining_date) from employee;
select * from employee order by first_name asc;
select * from employee order by first_name desc;
select first_name,salary from employee order by first_name asc, salary desc;
select * from employee where first_name='John';
select * from employee where first_name in('John','Roy');
select * from employee where first_name not in('John','Roy');
select * from employee where length(first_name) = 4 and right(first_name, 1) = 'n';
select *from employee where length(first_name) = 4 and left(first_name, 1) = 'J';
select * from employee where salary>600000;
select * from employee where salary<800000;
select * from employee where salary>500000 and salary<800000;
select * from employee where first_name in ('John','Michael');
select * from employee where year(joining_date)='2013';
select * from employee where month(joining_date)='January';
select * from employee where joining_date < '2013-01-01';
select * from employee where joining_date > '2013-01-31';
select date(joining_date),time(joining_date) from employee;
select date(joining_date),time(joining_date), microsecond(joining_date) from employee;
select first_name,incentive_date - joining_date from employee A inner join incentives B on A.employeeID=B.employee_ref_id;
select curdate();
select first_name from employee where last_name like '%\%%';
select replace(last_name,'%',' ') from employee;
select department,avg(salary) from employee group by department order by avg(salary) asc;
select department,max(salary) from employee group by department order by max(salary) asc;
select department,min(salary) from employee group by department order by min(salary) asc;
select year(joining_date) as joiningyear,month(joining_date) as joiningmonth, count(*) as numberofemployeesjoined from employee group by joiningyear, joiningmonth order by joiningyear, joiningmonth;
select department,sum(salary) as total_salary from employee group by department having total_salary > 800000 order by total_salary desc;
select a.first_name, b.incentive_amount from employee a join incentives b on a.employeeID = b.employee_ref_id;
select first_name,incentive_amount from employee A inner join incentives B on A.employeeID=B.employee_ref_id and incentive_amount >3000;
select first_name, incentive_amount from employee A left join incentives B on A.employeeID=B.employee_ref_id;
select first_name, ifnull(incentive_amount,0) from employee a left join incentives B on A.employeeID = B.employee_ref_id;
select first_name,ifnull(incentive_amount,0) from employee A right join incentives B on A.employeeID=B.employee_ref_id;
select first_name,(select ifnull(max(incentive_amount),0) from incentives where employee_ref_id=employeeID) max_incentive from employee;
select salary from employee order by salary desc limit 2;
select max(salary) from employee where salary < ( select max(salary) from employee);
select first_name from employee union select last_name from employee;
select * from employee where exists (select * from incentives);
select first_name, case first_name when 'John' then salary * .2 when 'Roy' then salary * .10 else salary * .15 end from employee;
select case department when 'Banking' then 'Bank Dept' when 'Insurance' then 'Insurance Dept' when 'Services' then 'ServicesDept'end from employee;
delete from employee where employeeID in (select employee_ref_id from incentives);
insert into employee (last_name) values ('Razer''');
update incentives set INCENTTIVE_AMOUNT='9000' where employeeID=(select employeeID from employee where first_name='pavan' );